### ISSUE TITLE
Custom library path

### ISSUE THREAD

**Issue by JtothaOern** [aptalca/docker-rdp-calibre#10]
Could you explain this a little bit more precisely?

> First add a new mount point for the library location in the docker run command. Example: -v /path/to/library:/library:rw

had no problem with that on my Synology

> Then add an environment variable (LIBRARYINTERNALPATH) to specify the internal library location for the webserver. Example: -e LIBRARYINTERNALPATH="/library"

Where do I do this exactly and how? :)

> When you fire up calibre the first time select your library location. Example: /library

I think this is even possible after the first run, isn't it?

**Comment by aptalca** [comment]
The option -e in the run command is for setting environment variables. In the synology interface just set an environment variable for the library internal path. 

My server is undergoing maintenance at the moment so I can't check, but I believe you can change the library location in the calibre gui
