### ISSUE TITLE
[Request] Add an Auto-Add feature.

### ISSUE THREAD

**Issue by miketweaver** [aptalca/docker-rdp-calibre#11]
I would like to request an "auto add" feature. Basically I'd like to be able to copy files to a folder on the Host machine (UnRaid) and have it automatically added to the Calibre library and database.

This can easily be done with cron.
I've sort of made it work in your docker, but I didn't add cron to your docker. Right now I just use cron from UnRaid to run the script. 
(`* * * * * /usr/bin/docker exec -i 16c3f6638615 '/addnew.sh' > /dev/null 2>&1`)

I created a new mountpoint and variable named `$TOADDPATH`
Then this takes the files from the `$TOADDPATH` location, puts them into the database, and then copies them to `$LIBRARYINTERNALPATH`. It then removes everything in the `$TOADDPATH` location.

/addnew.sh:

``` bash
#!/bin/bash
if [ -z "$TOADDPATH" ]; then
        echo "Environmental Variable 'TOADDPATH' is empty. Skipping adding new books"
else
        /opt/calibre/calibredb add -r -1 $TOADDPATH --with-library=$LIBRARYINTERNALPATH
        rm -r $TOADDPATH/*
fi
```

I don't know if the `-1` flag([doc](https://manual.calibre-ebook.com/generated/en/calibredb.html#adding-from-directories)) works well for everyone or not.

I think this would be very useful for a lot of people, and could probably be applied to your [other repo](https://github.com/aptalca/docker-calibre) as well.

--_Edit: fixed typo to script_

**Comment by aptalca** [comment]
Thanks for the code, I'll look into the feasibility of adding it in

**Comment by aptalca** [comment]
Since this is really a custom solution and you're using cron of host system, you can easily put the script in the config folder, and call the script from unraid's (or host's) cron via `docker exec -i [containername] /config/addnew.sh`

Since your script is custom and local, it would be OK to hardcode the paths.
