### ISSUE TITLE
Not detecting USB on qnap

### ISSUE THREAD

**Issue by heiserhorn** [aptalca/docker-rdp-calibre#13]
Hi

I  managed to install Calibre in the docker container.
I can access it but unfortunately it does not detect the ereader when USB connected to the NAS.

this is what I use to run the container:

docker run -d -t -i --name="RDP-Calibre" -e EDGE="1" -e WIDTH="1280" -e HEIGHT="720" --privileged=true -v /dev/bus/usb:/dev/bus/usb -p 8080:8080 aptalca/docker-rdp-calibre

in the container I get the following:

process 142: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory 
See the manual page for dbus-uuidgen to correct this issue. 
**: Failed to connect to DBUS session bus, with error: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message 
process 142: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory 
See the manual page for dbus-uuidgen to correct this issue. 
process 142: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory 
See the manual page for dbus-uuidgen to correct this issue. 

Any suggestion?

Cheers

Mike

**Comment by aptalca** [comment]
I never tried passing a usb through to a container but I believe it requires the drivers to be loaded in the host. Does your qnap have the drivers for it? 

Other than that I can't be of much help
