### ISSUE TITLE
Different Languages support

### ISSUE THREAD

**Issue by aam044** [aptalca/docker-rdp-calibre#15]
I am on Synology 6+
Everything works fine but when I connect to Calibre Client - I can not enter any text in code page different than english. (I do see titles and author in proper code page - just can not enter)
Web server works fine and allow me enter text in russian.

I believe it should be some sort of configuration of docker container - but documentation on this is very weak - and I did not find too much of info on this :(

**Comment by aptalca** [comment]
I just realized that is the case. Thanks for bringing it up.

This container uses a base by different author for the gui in web browser functionality. I suspect that the base is not allowing entry of non-english characters. I'll contact the author but he has not been very active lately.

**Comment by aptalca** [comment]
Did some testing and there is a workaround.

You can use the guacamole menu (ctrl+alt+shift) to type your non-english characters into the clipboard box, and then paste them into the fields in calibre

**Comment by aam044** [comment]
I found this workaround too - essentially when you copy paste it works. 
But as normal solution I think base docker should be updated. Would like to have this issue open until it is updated - but if you think it should be closed - I am fine :(
