### ISSUE TITLE
Cannot get container to run

### ISSUE THREAD

**Issue by exile259** [aptalca/docker-rdp-calibre#17]
I've been looking for a container to do exactly what this one does, but cannot for the life of me get this working. I create the container as

docker run -d --name="calibre" -e EDGE="1" -e WIDTH="1280" -e HEIGHT="720" -v /apps/calibre:/config:rw -v /data/books/calibre:/library:rw -e LIBRARYINTERNALPATH="/library" -e TZ="America/Chicago" -p 8088:8080 -p 8087:8081 aptalca/docker-rdp-calibre

and the logs show up as

[@]$ docker run -d --name=calibre -e EDGE="1" -e WIDTH="1280" -e HEIGHT="720" -v /apps/calibre:/config:rw -e TZ="America/Chicago" -p 8088:8080 -p 8087:8081 aptalca/docker-rdp-calibre
e4435a5f9e85e45df930cfa34e77cf70ba1d64992f44a7191f67e825e048b510
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
[@]$ docker logs -f calibre
*** Running /etc/my_init.d/00_config.sh...

Current default time zone: 'America/Chicago'
Local time is now:      Mon Jan 30 14:08:10 CST 2017.
Universal Time is now:  Mon Jan 30 20:08:10 UTC 2017.

*** Running /etc/my_init.d/01_user_config.sh...
usermod: no changes
usermod: no changes
usermod: no changes
*** Running /etc/my_init.d/02_app_config.sh...
*** Running /etc/my_init.d/firstrun.sh...
EDGE requested, updating to latest version
2017-01-30 14:08:10 URL:https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py [26007/26007] -> "-" [1]
Creating symlinks...
	Symlinking /opt/calibre/web2disk to /usr/bin/web2disk
	Symlinking /opt/calibre/lrs2lrf to /usr/bin/lrs2lrf
	Symlinking /opt/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
	Symlinking /opt/calibre/calibre-customize to /usr/bin/calibre-customize
	Symlinking /opt/calibre/markdown-calibre to /usr/bin/markdown-calibre
	Symlinking /opt/calibre/lrf2lrs to /usr/bin/lrf2lrs
	Symlinking /opt/calibre/calibre-debug to /usr/bin/calibre-debug
	Symlinking /opt/calibre/lrfviewer to /usr/bin/lrfviewer
	Symlinking /opt/calibre/ebook-viewer to /usr/bin/ebook-viewer
	Symlinking /opt/calibre/ebook-edit to /usr/bin/ebook-edit
	Symlinking /opt/calibre/calibre to /usr/bin/calibre
	Symlinking /opt/calibre/ebook-polish to /usr/bin/ebook-polish
	Symlinking /opt/calibre/calibredb to /usr/bin/calibredb
	Symlinking /opt/calibre/calibre-parallel to /usr/bin/calibre-parallel
	Symlinking /opt/calibre/ebook-convert to /usr/bin/ebook-convert
	Symlinking /opt/calibre/ebook-meta to /usr/bin/ebook-meta
	Symlinking /opt/calibre/ebook-device to /usr/bin/ebook-device
	Symlinking /opt/calibre/calibre-smtp to /usr/bin/calibre-smtp
	Symlinking /opt/calibre/calibre-server to /usr/bin/calibre-server
Setting up command-line completion...
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/calibre
Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________

	Traceback (most recent call last):
	  File "site-packages/calibre/linux.py", line 817, in setup_desktop_integration
	  File "site-packages/calibre/linux.py", line 802, in install_icons
	  File "site-packages/calibre/linux.py", line 796, in install_single_icon
	  File "subprocess.py", line 535, in check_call
	  File "subprocess.py", line 522, in call
	  File "subprocess.py", line 710, in __init__
	  File "subprocess.py", line 1335, in _execute_child
	OSError: [Errno 2] No such file or directory

Creating un-installer: /usr/bin/calibre-uninstall

There were 1 warnings

* Setting up desktop integration failed with error:

Installing to /opt/calibre
Downloading tarball signature securely...
Will download and install calibre-2.78.0-x86_64.txz 
Downloading calibre-2.78.0-x86_64.txz 
Downloaded 5.002252% 
Downloaded 10.004505% 
Downloaded 15.006757% 
Downloaded 20.009010% 
Downloaded 25.011262% 
Downloaded 30.013514% 
Downloaded 35.015767% 
Downloaded 40.018019% 
Downloaded 45.020272% 
Downloaded 50.022524% 
Downloaded 55.024776% 
Downloaded 60.027029% 
Downloaded 65.029281% 
Downloaded 70.031533% 
Downloaded 75.033786% 
Downloaded 80.036038% 
Downloaded 85.038291% 
Downloaded 90.040543% 
Downloaded 95.042795% 
Downloaded 62067400 bytes 
Checking downloaded file integrity... 
Extracting files to /opt/calibre ...
Extracting application files... 
Run "calibre" to start calibre 
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 63
ok: run: openbox: (pid 72) 0s
Starting xrdp!
guacd[80]: INFO:	Guacamole proxy daemon (guacd) version 0.9.7 started
guacd[80]: INFO:	Listening on host 127.0.0.1, port 4822
InitOutput:

X11rdp, an X server for xrdp
Version 0.9.0
Copyright (C) 2005-2015 Jay Sorg
See http://www.xrdp.org for information on xrdp.
Underlying X server release 10903000, The X.Org Foundation
Screen width 1280 height 720 depth 16 bpp 16
dpix 100 dpiy 100
buffer size 1843200
30/01/17 14:08:29 kill disconencted [0] timeout [60] sec
pRRScrPriv 0x24b2740
rdpScreenInit: ret 1
InitOutput: out
[dix] Could not init font path element /usr/share/fonts/X11/misc/, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/TTF/, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/OTF/, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
rdpSpriteDeviceCursorInitialize:
Jan 30 14:08:29 e4435a5f9e85 syslog-ng[84]: syslog-ng starting up; version='3.5.3'
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: sink_process_msg: not running
E: close_send:
W: [pulseaudio] authkey.c: Failed to open cookie file '/nobody/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authorization key '/nobody/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/nobody/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authorization key '/nobody/.pulse-cookie': No such file or directory
W: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.Spawn.ExecFailed: //bin/dbus-launch terminated abnormally without any error message
W: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.Spawn.ExecFailed: //bin/dbus-launch terminated abnormally without any error message
rdpPointerWarpCursor:
rdpPointerNewEventScreen:
InitInput:
rdpMouseCtrl:
rdpChangeKeyboardControl:
rdpChangeKeyboardControl:
Obt-Message: Xinerama extension is not present on the server
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml"
Jan 30, 2017 2:08:29 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/common/classes], exists: [false], isDirectory: [false], canRead: [false]
Jan 30, 2017 2:08:29 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/common], exists: [false], isDirectory: [false], canRead: [false]
Starting X app...
Jan 30, 2017 2:08:30 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server/classes], exists: [false], isDirectory: [false], canRead: [false]
Jan 30, 2017 2:08:30 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server], exists: [false], isDirectory: [false], canRead: [false]
Jan 30, 2017 2:08:30 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
Jan 30, 2017 2:08:30 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared], exists: [false], isDirectory: [false], canRead: [false]
rdpRRGetInfo:
rdpRRRegisterSize: width 1280 height 720
rdpRRGetPanning:
Warning: Missing charsets in String to FontSet conversion
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
Jan 30, 2017 2:08:31 PM org.apache.catalina.startup.Catalina initDirs
SEVERE: Cannot find specified temporary folder at /tmp/tomcat7-tomcat7-tmp
rdpRRGetPanning:
Jan 30, 2017 2:08:32 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Jan 30, 2017 2:08:32 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 1027 ms
Jan 30, 2017 2:08:32 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Jan 30, 2017 2:08:32 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.52 (Ubuntu)
Jan 30, 2017 2:08:32 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/ROOT.war
Jan 30, 2017 2:08:32 PM org.apache.catalina.core.StandardContext postWorkDirectory
WARNING: Failed to create work directory [/var/lib/tomcat7/work/Catalina/localhost/_] for context []
14:08:38.497 [localhost-startStop-1] INFO  o.g.g.n.b.r.a.BasicTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
14:08:39.023 [localhost-startStop-1] WARN  o.g.g.n.b.extension.ExtensionModule - The "auth-provider" and "lib-directory" properties are now deprecated. Please use the "extensions" and "lib" directories within GUACAMOLE_HOME instead.
14:08:39.573 [localhost-startStop-1] INFO  o.g.g.n.b.w.t.WebSocketTunnelModule - Loading Tomcat 7 WebSocket support...
Jan 30, 2017 2:08:43 PM org.apache.catalina.util.SessionIdGenerator createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [3,301] milliseconds.
Jan 30, 2017 2:08:44 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.activeconnection.ActiveConnectionRESTService as a root resource class
Jan 30, 2017 2:08:44 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.clipboard.ClipboardRESTService as a root resource class
Jan 30, 2017 2:08:44 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.connectiongroup.ConnectionGroupRESTService as a root resource class
Jan 30, 2017 2:08:44 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.connection.ConnectionRESTService as a root resource class
Jan 30, 2017 2:08:44 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.language.LanguageRESTService as a root resource class
Jan 30, 2017 2:08:44 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.schema.SchemaRESTService as a root resource class
Jan 30, 2017 2:08:44 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.auth.TokenRESTService as a root resource class
Jan 30, 2017 2:08:44 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.user.UserRESTService as a root resource class
Jan 30, 2017 2:08:44 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.codehaus.jackson.jaxrs.JacksonJsonProvider as a provider class
Jan 30, 2017 2:08:44 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.17.1 02/28/2013 12:47 PM'
Jan 30, 2017 2:08:44 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.codehaus.jackson.jaxrs.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
Jan 30, 2017 2:08:46 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.activeconnection.ActiveConnectionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:46 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.clipboard.ClipboardRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:46 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.connectiongroup.ConnectionGroupRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:46 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.connection.ConnectionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:46 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.language.LanguageRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:46 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.schema.SchemaRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:46 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.auth.TokenRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:46 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.user.UserRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:46 PM org.apache.jasper.EmbeddedServletOptions <init>
SEVERE: The scratchDir you specified: /var/lib/tomcat7/work/Catalina/localhost/_ is unusable.
Jan 30, 2017 2:08:46 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/guacamole.war
Jan 30, 2017 2:08:46 PM org.apache.catalina.core.StandardContext postWorkDirectory
WARNING: Failed to create work directory [/var/lib/tomcat7/work/Catalina/localhost/guacamole] for context [/guacamole]
14:08:50.306 [localhost-startStop-1] INFO  o.g.g.n.b.r.a.BasicTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
14:08:50.546 [localhost-startStop-1] WARN  o.g.g.n.b.extension.ExtensionModule - The "auth-provider" and "lib-directory" properties are now deprecated. Please use the "extensions" and "lib" directories within GUACAMOLE_HOME instead.
14:08:50.609 [localhost-startStop-1] INFO  o.g.g.n.b.w.t.WebSocketTunnelModule - Loading Tomcat 7 WebSocket support...
Jan 30, 2017 2:08:51 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.activeconnection.ActiveConnectionRESTService as a root resource class
Jan 30, 2017 2:08:51 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.clipboard.ClipboardRESTService as a root resource class
Jan 30, 2017 2:08:51 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.connectiongroup.ConnectionGroupRESTService as a root resource class
Jan 30, 2017 2:08:51 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.connection.ConnectionRESTService as a root resource class
Jan 30, 2017 2:08:51 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.language.LanguageRESTService as a root resource class
Jan 30, 2017 2:08:51 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.schema.SchemaRESTService as a root resource class
Jan 30, 2017 2:08:51 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.auth.TokenRESTService as a root resource class
Jan 30, 2017 2:08:51 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.glyptodon.guacamole.net.basic.rest.user.UserRESTService as a root resource class
Jan 30, 2017 2:08:51 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.codehaus.jackson.jaxrs.JacksonJsonProvider as a provider class
Jan 30, 2017 2:08:51 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.17.1 02/28/2013 12:47 PM'
Jan 30, 2017 2:08:51 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.codehaus.jackson.jaxrs.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
Jan 30, 2017 2:08:52 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.activeconnection.ActiveConnectionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:52 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.clipboard.ClipboardRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:52 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.connectiongroup.ConnectionGroupRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:52 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.connection.ConnectionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:52 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.language.LanguageRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:52 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.schema.SchemaRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:52 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.auth.TokenRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:52 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.glyptodon.guacamole.net.basic.rest.user.UserRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
Jan 30, 2017 2:08:52 PM org.apache.jasper.EmbeddedServletOptions <init>
SEVERE: The scratchDir you specified: /var/lib/tomcat7/work/Catalina/localhost/guacamole is unusable.
Jan 30, 2017 2:08:52 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Jan 30, 2017 2:08:52 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 20181 ms

Any thoughts on how to resolve this?

**Comment by aptalca** [comment]
I just saw this.

The last line indicates that the server started. What is the issue you are encountering?

**Comment by exile259** [comment]
I have gotten the container functioning, but if you have a moment to
assist: I cannot seem to get it to retain a library after rebuilding the
container. It will restart, but if I delete the container (not removing the
config directory) I have to reimport all of my libraries. Also, is there
anyway to require authentication to access the page?  I haven't found a
variable that works or an option within the application itself.

**Comment by aptalca** [comment]
You are probably switching the library location back and forth between /config and /library

In your original post, you say that you are mapping the /library location and passing the variable for internal library path, but your log below that shows no mapping and no environment variable.

Libraryinternal path setting is really for advanced users and I do not provide support for it. I suggest you get it set up with the /config as the library location, map the other folder so you import books from there, but your library, database and configuration files will all be in the /config folder

There is no support for authentication for the gui

**Comment by exile259** [comment]
so there is no way to control access to the gui?

**Comment by aptalca** [comment]
No there isn't

**Comment by exile259** [comment]
thanks for the info.
