### ISSUE TITLE
auto import of books

### ISSUE THREAD

**Issue by partymike** [aptalca/docker-rdp-calibre#19]
have everything setup and working fine, all initial problems proved to be permission errors (running on synology although using linuxserver.io docker images with PGID permissions proved to be very easy setup - any plans to use this method?)

But I cannot get calibre to auto import books, import folder is set to /books and I can manually import from this folder using the "Add Books" menu...I restarted calibre as advised but nothing changed.

Any ideas?

**Comment by aptalca** [comment]
I don't believe calibre auto imports books. You have to import through the gui.

**Comment by partymike** [comment]
before moving to this docker version I ran on windows and the import (same settings) ran great...any books dropped into that folder would be hoovered up into calibre - you can see the auto import settings in "preferences - adding books - automatic adding"

**Comment by aptalca** [comment]
I wasn't even aware of that feature. 

I found this thread: https://www.mobileread.com/forums/showthread.php?p=2712253#post2712253
where the author of calibre (kavidgoyal) talks about it. Everyone seems to refer to windows. Maybe it's windows only? I'm not sure. You should ask them as it's an internal feature of calibre.
