### ISSUE TITLE
Username/Password for Calibre Server?

### ISSUE THREAD

**Issue by sanicki** [aptalca/docker-rdp-calibre#21]
On the [Docker Store](https://store.docker.com/community/images/aptalca/docker-rdp-calibre) you link to this URL for instuctions on setting the Calibre Server username and password, but the link is bad.

https://lime-technology.com/forum/index.php?topic=39413.msg421321#msg421321

**Comment by aptalca** [comment]
Oh boy, they redid the forums and broke some links apparently. It will take me a while finding that post.

**Comment by sanicki** [comment]
Is this it?

https://forums.lime-technology.com/topic/37735-support-aptalcas-docker-templates/?page=35#comment-511567

**Comment by aptalca** [comment]
That's the one. But keep in mind that the changes will survive container start / stop, but not recreation

**Comment by sanicki** [comment]
If you're editing your post in the Docker Store I subsequently found this post of yours with more complete instructions:

https://forums.lime-technology.com/profile/7767-aptalca/content/?type=forums_topic_post&page=31
