### ISSUE TITLE
Cannot Setup Calibre

### ISSUE THREAD

**Issue by mccorkled** [aptalca/docker-rdp-calibre#26]
I have tried for several weeks now to get this program working and I have had no success. When I try to setup the initial database I get an error. Then if I try to use an existing database I get another error. I am on a Synology device using Docker. I have setup many containers and I am quite certain that I have this setup right. 

![screen shot 2017-10-04 at 12 38 25 pm](https://user-images.githubusercontent.com/13697804/31592223-b223dd94-b1f4-11e7-8e25-9ac56d54e9e9.png)
![screen shot 2017-10-04 at 12 40 08 pm](https://user-images.githubusercontent.com/13697804/31592224-b22fd0cc-b1f4-11e7-825d-f9a6cd19bb03.png)

Thanks :)

**Comment by aptalca** [comment]
It seems you mapped /books as the library location but you're having permission issues. Make sure the permissions are correct, or use /config as the library location

**Comment by mccorkled** [comment]
Is the library location where the actual books are going to be stored? Usually for dockers contailers /config is where the config files go, and then /whatever is where the library items go such as /movies, /tv shows, or /books. 

I set the UID and GID so there shouldn't be any permission issues. 

Thanks

**Comment by simistef** [comment]
having the same exact error. what is the fix for this ?

**Comment by mccorkled** [comment]
Just make a directory in the /Books folder called /calibre.
Books/calibre

It's a permission issue within Synology
