### ISSUE TITLE
Calibre start exception

### ISSUE THREAD

**Issue by gammon59** [aptalca/docker-rdp-calibre#28]
I ran docker-rdp-calibre for months on Synology DSM 5.2 but suddenly (after a reboot of my NAS) Calibre is not able to start anymore. Here is the screen cast of the error it trows :  
![calibre_error](https://user-images.githubusercontent.com/8709287/32417032-50e5a37c-c253-11e7-893d-694e6062f63c.jpg)

Any idea how I can fix that ?
Thanks for your help.

Francois

**Comment by MikeStromberg** [comment]
Identical error here. It's been running great until now.

**Comment by Tiemichael** [comment]
(Most likely) same here ...
Started Nov 2nd.
I can access the Content-Server, but the Calibre-GUI stays black (after connecting to Calibre-Session)

**Comment by aptalca** [comment]
Latest calibre doesn't work in this image. Please set the edge variable to 0 while I investigate

**Comment by Tiemichael** [comment]
According to https://www.mobileread.com/forums/showpost.php?p=3605743&postcount=6 this issues should be fixed with the next version ...

**Comment by danfozzy** [comment]
that doesnt fix our issue, 3.11.1 still has the same issue

**Comment by aptalca** [comment]
@danfozzy that commit was merged after 3.11.1, the next release should hopefully fix it.

**Comment by Tiemichael** [comment]
Upgrade 3.12 is working for me!
Thanks!

**Comment by aptalca** [comment]
Yup , looks like the latest version is working. Closing this.
