### ISSUE TITLE
Can not read/write to any mounts

### ISSUE THREAD

**Issue by darrylmorley** [aptalca/docker-rdp-calibre#33]
Hi,

I'm hoping somebody may pick this up.

I am running docker on Ubuntu 16.04 trying to get this to work, I can not create my library in /config as per the instructions provided due to the error, the directory must be empty. No alternative mounts created are useable...

**Comment by brambaars** [comment]
I'm experiencing the same issue, on my Synology.
In other containers it works flawlessly. I tried many things: adding PGID and PUID, entering/updating my user ID and group ID, but in this package I just cannot get the writing rights on my mounted folders... :(

**Comment by legobuild** [comment]
Same issue here. I run docker on a ubuntu server, all my media is on a synology nas. I have my ebook library mounted at /media/books in ubuntu and added that as a volume in the docker container (at /books). Once in Calibre, any attempts to access /books result in a permissions error.

The same setup works for plex with movies and music.
