### ISSUE TITLE
Dashboard GUI does not show

### ISSUE THREAD

**Issue by spsanderson** [aptalca/docker-rdp-calibre#37]
I just installed the docker image, did all my setup in my docker-compose. When taken to the calibre dashboard nothing shows, just a black screen.

Container Log
https://pastebin.com/bN3BnLMc

**Comment by bodybybuddha** [comment]
Shot in the dark - if you are still having the same issue @spsanderson: I had a similar problem with my docker-compose file.  I got mine to work by removing the quotes around the width & height environment variables. 

environment:
      - EDGE=0 
      - WIDTH=1024 
      - HEIGHT=720 
      - TZ=America/New_York

**Comment by spsanderson** [comment]
Interesting will give that s try

Steven P Sanderson II, MPH
