### ISSUE TITLE
Request: container like this but for Google music manager

### ISSUE THREAD

**Issue by blackbarn** [aptalca/docker-rdp-calibre#6]
Wasn't sure where else to put it. Ever thought of doing something similar to this repo for Google music manager?

**Comment by aptalca** [comment]
This guy created a docker container for google music manager: https://github.com/ruippeixotog/docker-google-musicmanager

You have to vnc in, but I let him know about the gui baseimage I used for in browser vnc use. If he's not interested, I might take a look when I have the time.
