### ISSUE TITLE
How to update Calibre

### ISSUE THREAD

**Issue by JtothaOern** [aptalca/docker-rdp-calibre#9]
First of all:  thank you very much for this docker file. 
I have both, GUI and server, up and running on a Synology DS 412+ with DSM 6. Seems to work fine. 

When I start the GUI I get a notification that there is a newer version of Calibre available (installed version is 2.33 and the newer one is 2.53.0).
Is there an update command which I can start from the terminal?

**Comment by JtothaOern** [comment]
Found it out myself:

Just use the terminal and paste in (CTRL+A and then CTRL+V on Synology Docker Terminal) the following:
sudo -v && wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"

**Comment by aptalca** [comment]
Or you can change the edge variable in the run command to 1 and it will update itself on container start ;-)

**Comment by JtothaOern** [comment]
I read that too, but I think you can't use the run command with Docker on Synology. 
Maybe that or I am just blind ;)

**Comment by aptalca** [comment]
If you're using the synology interface,  just set an environment variable where edge=1

**Comment by JtothaOern** [comment]
Ah, thanks for the hint!
